version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    extra_hosts:
      - "share-posts.test:127.0.0.1"
    hostname: share-posts.test
    domainname: test
    ports:
      - 8000:80
    volumes: ['./share-posts:/var/www/html']
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: share_posts
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '3333:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
  php-apache-environment:
  db-data:
    driver: local
 